import {loadExistingComparison} from '../Build/JS/Application/mastering-preview.js';
import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,writeFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';
import {Service} from '../Build/JS/Application/service.js';import {Engine} from '../Build/JS/Adapters/node/engine/engine.js';import {createLocalApplication} from '../Build/JS/Application/local-application.js';import {call} from '../Build/JS/Application/api.js';
import {ProcessingQueue} from '../Build/JS/Adapters/node/runtime/processing-queue.js';
test('background enqueue does not inherit and escape the active lane',async()=>{const q=new ProcessingQueue();let nested,order=[];await q.run('parent',async()=>{nested=q.enqueue('child',async()=>{order.push('child');});order.push('parent');await new Promise(r=>setTimeout(r,10));assert.deepEqual(order,['parent']);});await nested;assert.deepEqual(order,['parent','child']);q.shutdown();});
test('mastering auto-prepares current versions before playback and downloads fixed A/B in selected formats',{timeout:60000},async t=>{
 const root=await mkdtemp(join(tmpdir(),'aidaw-prepare-')),engine=new Engine(resolve('Core/Build/Native/bin/aidaw-engine'),{home:process.cwd()}),service=new Service(root,engine),api=(n,a={})=>call(createLocalApplication(service),n,a);
 t.after(async()=>{await service.close();await rm(root,{recursive:true,force:true});});let renders=0;const render=engine.render.bind(engine);engine.render=async(...args)=>{renders++;return render(...args);};
 const frames=48000,wav=Buffer.alloc(44+frames*4);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(2,22);wav.writeUInt32LE(48000,24);wav.writeUInt32LE(192000,28);wav.writeUInt16LE(4,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(frames*4,40);for(let i=0;i<frames;i++){const v=Math.round(4000*Math.sin(i*2*Math.PI*440/48000));wav.writeInt16LE(v,44+i*4);wav.writeInt16LE(v,46+i*4);}await writeFile(join(root,'tone.wav'),wav);
 await api('project_create',{project_id:'album',kind:'mastering',name:'Album'});const asset=await api('asset_import',{project_id:'album',path:join(root,'tone.wav'),role:'source'});
 const added=await api('mastering_add_song',{project_id:'album',base_revision:0,request_id:'original',song_id:'song',name:'Tone',asset_id:asset.id});assert.equal((await service.wait(added.preparation.job_id)).state,'succeeded');assert.equal(renders,1);
 const version=await api('mastering_create_version',{project_id:'album',base_revision:1,request_id:'quiet',song_id:'song',parent_version_id:'original',label:'Quiet',input_gain_db:-6});const repeated=await api('mastering_prepare',{project_id:'album'});assert.equal(repeated.job_id,version.preparation.job_id);assert.equal((await service.wait(repeated.job_id)).state,'succeeded');assert.equal(renders,2);
 await api('project_apply',{project_id:'album',base_revision:2,request_id:'slots',operations:[{op:'set_comparison',song_id:'song',slot:'b',selection:{kind:'version',version_id:'quiet'}}]});
 const prepared=await api('mastering_prepare',{project_id:'album'});await service.wait(prepared.job_id);assert.equal(renders,2);
 const base={project_id:'album',song_id:'song',revision:3};
 for(const options of [{format:'wav',bit_depth:16,sample_rate:44100},{format:'wav',bit_depth:32,sample_rate:96000},{format:'flac',bit_depth:24,sample_rate:88200},{format:'mp3',bitrate_kbps:192,sample_rate:44100}]){const out=await api('mastering_download',{...base,comparison:'b',options});assert.equal(out.version_id,'quiet');assert.equal(out.sample_rate,options.sample_rate);assert.ok(out.sha256);}
 const a=await api('mastering_download',{...base,comparison:'a'});assert.equal(a.version_id,'original');assert.equal(renders,2,'encoding must reuse prepared PCM');
 const document=await service.readDocument('album'),pair=await loadExistingComparison(service,document,{song_id:'song',comparison:'b'});assert.equal(pair.paths.length,2);assert.equal(renders,2);
 const describe=engine.describe.bind(engine);engine.describe=async()=>({...await describe(),content_fingerprint:'transport-update'});assert.deepEqual((await loadExistingComparison(service,document,{song_id:'song',comparison:'b'})).paths,pair.paths);engine.describe=describe;
 const savedPrepare=service.prepareMastering;service.prepareMastering=()=>{throw Error('Selection must not render');};await service.selectActiveContext({project_id:'album'});service.prepareMastering=savedPrepare;
 await rm(pair.paths[0]);await assert.rejects(api('playback_start',{...base,comparison:'a',start_frame:'0'}),/未生成/);assert.equal(renders,2,'transport must not render missing audio');
 await assert.rejects(api('mastering_download',{...base,comparison:'b',options:{format:'mp3',sample_rate:96000}}),/MP3/);
});
