import test from 'node:test';import assert from 'node:assert/strict';
import {projectFiles} from '../Source/Desktop/runtime/project-files.mjs';
function fixture({kind='composition',paths=['one.wav','two.wav'],fail=false,destination='new',renderFail=false}={}){
 const calls=[],messages=[];let n=0,chosen;const api=async(name,args)=>{calls.push({name,args});if(name==='file_import'){if(fail&&args.path==='two.wav')throw Error('bad audio');return {id:args.path};}if(name==='project_document')return {revision:7};if(name==='project_list')return [{project_id:'existing',kind:'mastering',name:'Album'}];if(name==='render_start'||name==='separation_start')return {job_id:'job'};if(name==='job_status')return renderFail?{state:'failed',error:'render failed'}:{state:'succeeded',files:[{path:'/output.wav',format:'wav'}]};return {};};
 const ui=projectFiles({api,host:{chooseAudioFiles:async()=>paths,notify:m=>messages.push(m),form:async()=>({destination,name:'New'})},getState:()=>({projectId:'source',document:{kind,name:'Song'}}),stop:async()=>calls.push({name:'stop'}),reload:async()=>{},refresh:async()=>{},chooseProject:async p=>chosen=p,id:()=>`id${++n}`,delay:async()=>{}});
 return {ui,calls,messages,chosen:()=>chosen};
}
test('multiple imports preserve successful assets and report failures without inventing tracks',async()=>{const f=fixture({fail:true});await f.ui.importAudio();assert.equal(f.calls.filter(c=>c.name==='file_import').length,2);assert.ok(!f.calls.some(c=>c.name==='mastering_add_song'));assert.match(f.messages[0],/1件/);assert.match(f.messages[0],/two/);const cancelled=fixture({paths:[]});await cancelled.ui.importAudio();assert.equal(cancelled.calls.length,0);});
test('mastering imports add songs against fresh revisions',async()=>{const f=fixture({kind:'mastering'});await f.ui.importAudio();const calls=f.calls.filter(c=>c.name==='mastering_add_song');assert.equal(calls.length,2);assert.ok(calls.every(c=>c.args.base_revision===7&&c.args.project_id==='source'));});
test('send renders first, adds to existing album and opens destination',async()=>{const f=fixture({destination:'existing'});await f.ui.send('mastering');assert.ok(!f.calls.some(c=>c.name==='project_create'));assert.equal(f.chosen(),'existing');assert.equal(f.calls.find(c=>c.name==='file_import').args.path,'/output.wav');const bad=fixture({renderFail:true});await assert.rejects(bad.ui.send('mastering'),/render failed/);assert.ok(!bad.calls.some(c=>c.name==='project_create'||c.name==='file_import'));});
test('separation send creates a new project and waits for its stems',async()=>{const f=fixture();await f.ui.send('separation');assert.equal(f.calls.find(c=>c.name==='project_create').args.kind,'separation');assert.ok(f.calls.some(c=>c.name==='separation_start'));assert.ok(f.chosen());});
test('mastering image import does not add an audio song',async()=>{const f=fixture({kind:'mastering',paths:['cover.PNG']});await f.ui.importAudio();assert.equal(f.calls.filter(c=>c.name==='file_import').length,1);assert.ok(!f.calls.some(c=>c.name==='mastering_add_song'));});
