import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile,mkdir} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {unzipSync} from 'fflate';
import {Service} from '../Build/JS/Application/service.js';
import {startSeparation,exportSeparation,audibleStems} from '../Build/JS/Application/separation.js';
import {ingest} from '../Build/JS/Adapters/node/workspace/assets.js';
import {saveProject,importBundle} from '../Build/JS/Adapters/node/workspace/package.js';
import {SpleeterSeparator} from '../Build/JS/Adapters/node/media/spleeter.js';
const run=promisify(execFile),ff=process.env.AIDAW_FFMPEG??'ffmpeg';
const fake={id:'test-only',model:'scaled-fixture',async separate({path,outputDirectory,signal}){await mkdir(outputDirectory,{recursive:true});const output=[];for(const [i,name]of ['vocals','drums','bass','other'].entries()){const dest=join(outputDirectory,`${name}.wav`);await run(ff,['-v','error','-y','-i',path,'-af',`volume=${(i+1)/10}`,'-c:a','pcm_f32le',dest],{signal});output.push({name,path:dest});}return output;}};
async function fixture(separator=fake){const root=await mkdtemp(join(tmpdir(),'aidaw-separation-'));const s=new Service(root,undefined,{separator});await s.create({project_id:'separate',name:'Separation fixture',kind:'separation',bpm:120,length_ticks:3840,meter:[4,4]});const path=join(root,'source.wav');await run(ff,['-v','error','-y','-f','lavfi','-i','sine=frequency=220:duration=2','-ar','48000','-ac','2','-c:a','pcm_f32le',path]);const asset=await ingest(s,'separate',path,'source');return {root,s,asset,async close(){await s.close();await rm(root,{recursive:true,force:true});}};}
async function separate(f,request='first'){const job=await startSeparation(f.s,{project_id:'separate',source_asset_id:f.asset.id,base_revision:0,request_id:request});const result=await f.s.wait(job.job_id);assert.equal(result.state,'succeeded',result.error);return result;}
test('separation saves provenance, revisions and portable history; retry never repeats inference',async()=>{const f=await fixture();try{const result=await separate(f);const doc=await f.s.readDocument('separate');assert.equal(doc.kind,'separation');assert.equal(doc.composition.tracks.length,4);assert.equal(doc.separation.source_asset_id,f.asset.id);assert.equal(doc.revision,1);const replay=await startSeparation(f.s,{project_id:'separate',source_asset_id:f.asset.id,base_revision:0,request_id:'first'});assert.equal(replay.job_id,result.id);assert.equal(replay.replayed,true);await assert.rejects(startSeparation(f.s,{project_id:'separate',source_asset_id:f.asset.id,base_revision:1,request_id:'first'}),/reused/);const bundle=await saveProject(f.s,'separate',{});await importBundle(f.s,bundle.output,'imported');assert.equal((await f.s.readDocument('imported')).kind,'separation');await f.s.restore({project_id:'separate',base_revision:1,revision:0,request_id:'restore'});assert.equal((await f.s.readDocument('separate')).composition.tracks.length,0);}finally{await f.close();}});
test('all-stem ZIP ignores mute/solo; fixed-revision mix exports solo and rejects empty selection',async()=>{const f=await fixture();try{await separate(f);await f.s.apply({project_id:'separate',base_revision:1,request_id:'solo',operations:[{op:'set_track',track_id:'vocals',changes:{solo:true}},{op:'set_track',track_id:'drums',changes:{mute:true}}]});const zip=await exportSeparation(f.s,{project_id:'separate',request_id:'zip',revision:2,kind:'stems',format:'wav'});const z=await f.s.wait(zip.job_id);assert.equal(z.state,'succeeded',z.error);assert.deepEqual(Object.keys(unzipSync(await readFile(z.output))).sort(),['bass.wav','drums.wav','manifest.json','other.wav','vocals.wav']);const mix=await exportSeparation(f.s,{project_id:'separate',request_id:'mix',revision:2,kind:'mix',format:'wav'});const m=await f.s.wait(mix.job_id);assert.equal(m.state,'succeeded',m.error);assert.deepEqual(m.report.stems.map(s=>s.id),['vocals']);assert.equal((await f.s.engine.analyze({path:m.output})).sample_rate,48000);await f.s.apply({project_id:'separate',base_revision:2,request_id:'mute-solo',operations:['vocals','drums','bass','other'].map(track_id=>({op:'set_track',track_id,changes:{mute:true,solo:false}}))});const empty=await exportSeparation(f.s,{project_id:'separate',request_id:'empty',revision:3,kind:'mix',format:'wav'});assert.equal((await f.s.wait(empty.job_id)).state,'failed');}finally{await f.close();}});
test('failed separation never publishes partial stems and rejects reference input',async()=>{const f=await fixture({id:'fail',model:'test',async separate(){throw Error('inference failed');}});try{const job=await startSeparation(f.s,{project_id:'separate',source_asset_id:f.asset.id,base_revision:0,request_id:'fail'});assert.equal((await f.s.wait(job.job_id)).state,'failed');assert.equal((await f.s.readDocument('separate')).revision,0);const reference=await ingest(f.s,'separate',join(f.root,'source.wav'),'reference');const j=await startSeparation(f.s,{project_id:'separate',source_asset_id:reference.id,base_revision:0,request_id:'ref'});assert.match((await f.s.wait(j.job_id)).error,/source asset/);}finally{await f.close();}});
test('one solo overrides retained mute settings',()=>{assert.deepEqual(audibleStems([{mute:true,solo:true},{mute:false,solo:true}]),[{mute:true,solo:true}]);});
test('installed Spleeter performs actual four-stem inference',{skip:process.env.AIDAW_TEST_SEPARATION!=='1',timeout:240000},async()=>{const f=await fixture(new SpleeterSeparator(resolve('.')));try{const result=await separate(f);assert.equal(result.files.length,4);assert.equal(new Set(result.files.map(f=>f.sha256)).size,4);for(const file of result.files){const a=await f.s.engine.analyze({path:file.path});assert.equal(a.sample_rate,48000);assert.equal(a.channels,2);assert.equal(a.duration_seconds,2);}}finally{await f.close();}});
test('cancellation and concurrent edits do not overwrite authored stems',async()=>{
 let entered,release;const started=new Promise(r=>entered=r),blocked=new Promise(r=>release=r);
 const separator={id:'blocked',model:'test',async separate(args){entered();await Promise.race([blocked,new Promise((_,reject)=>args.signal.addEventListener('abort',()=>reject(Error('cancelled')),{once:true}))]);return fake.separate(args);}};
 const f=await fixture(separator);try{const j=await startSeparation(f.s,{project_id:'separate',source_asset_id:f.asset.id,base_revision:0,request_id:'cancel'});await started;await f.s.cancel(j.job_id);assert.equal((await f.s.jobStatus(j.job_id)).state,'cancelled');assert.equal((await f.s.readDocument('separate')).revision,0);
 }finally{release();await f.close();}
 let notify,resume;const wait=new Promise(r=>notify=r),continueJob=new Promise(r=>resume=r);const g=await fixture({id:'conflict',model:'test',async separate(args){notify();await continueJob;return fake.separate(args);}});
 try{const j=await startSeparation(g.s,{project_id:'separate',source_asset_id:g.asset.id,base_revision:0,request_id:'conflict'});await wait;
 await g.s.workspace.change({projectId:'separate',baseRevision:0,requestId:'other-editor',fingerprint:'other'},async doc=>({...doc,name:'Concurrent edit',revision:1}));resume();const done=await g.s.wait(j.job_id);assert.equal(done.state,'failed');assert.match(done.error,/Revision conflict/);assert.equal((await g.s.readDocument('separate')).name,'Concurrent edit');assert.equal((await g.s.readDocument('separate')).composition.tracks.length,0);
 }finally{resume();await g.close();}
});

import {projectWaveform} from '../Build/JS/Adapters/node/media/waveform.js';
test('separated audio supplies four measured waveform layers without a mix render',async()=>{const f=await fixture();try{await separate(f);const wave=await projectWaveform(f.s,{project_id:'separate',bins:64});assert.equal(wave.role,'stems');assert.equal(wave.layers.length,4);assert.deepEqual(wave.layers.map(l=>l.track_id),['vocals','drums','bass','other']);for(const l of wave.layers){assert.equal(l.peaks.length,64);assert.ok(l.peaks.some(p=>p>0));}assert.ok(Math.max(...wave.layers[0].peaks)<Math.max(...wave.layers[3].peaks));}finally{await f.close();}});

test('engine toggle stores both results and reuses immutable stems without inference',async()=>{
 let calls=0;const standard={...fake,id:'spleeter',model:'4stems-16kHz'},alternate={...fake,id:'demucs',model:'htdemucs',async separate(args){calls++;return fake.separate(args);}};
 const f=await fixture(standard);f.s.separators.demucs=alternate;
 try{await separate(f);let doc=await f.s.readDocument('separate');
 const runEngine=async(engine,request)=>{const job=await startSeparation(f.s,{project_id:'separate',source_asset_id:f.asset.id,base_revision:doc.revision,request_id:request,engine});const result=await f.s.wait(job.job_id);assert.equal(result.state,'succeeded',result.error);doc=await f.s.readDocument('separate');return result;};
 await runEngine('demucs','to-demucs');assert.equal(doc.separation.engine,'demucs');assert.ok(doc.separation.variants.spleeter);assert.ok(doc.separation.variants.demucs);
 assert.equal((await runEngine('spleeter','to-spleeter')).cached,true);assert.equal((await runEngine('demucs','back-demucs')).cached,true);assert.equal(calls,1);
 }finally{await f.close();}
});
