import {renderWaveformSvg} from '../../Core/Source/ControlSurface/waveform.mjs';
export const time=(frames,rate)=>{const s=Math.floor(frames/rate);return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;};
export function element(doc,tag,className,text){const el=doc.createElement(tag);if(className)el.className=className;if(text)el.textContent=text;return el;}
export function createDisplay(root){const d=root.ownerDocument,art=element(d,'img','surface-artwork'),box=element(d,'div','display'),meta=element(d,'div','meta'),status=element(d,'p','state'),info=element(d,'div','song-info'),tempo=element(d,'span','tempo'),title=element(d,'h2'),readout=element(d,'div','readout'),kind=element(d,'div','project-kind'),clock=element(d,'div','playback-time');readout.append(kind,clock);info.append(status,tempo);meta.append(info,title);box.append(meta,readout);art.alt='';art.hidden=true;art.setAttribute('aria-hidden','true');let artworkUrl=null;art.onload=()=>{if(artworkUrl){art.hidden=false;root.classList.add('has-artwork');}};art.onerror=()=>{art.hidden=true;root.classList.remove('has-artwork');};root.classList.remove('has-artwork');root.append(art,box);return s=>{if(artworkUrl!==(s.artworkUrl??null)){artworkUrl=s.artworkUrl??null;art.hidden=true;root.classList.remove('has-artwork');if(artworkUrl)art.src=artworkUrl;else art.removeAttribute('src');}title.textContent=s.title;tempo.hidden=!(Number.isFinite(s.tempoBpm)&&s.tempoBpm>0);tempo.textContent=tempo.hidden?'':`${s.tempoBpm} BPM`;const selected=s.comparisons?.find(c=>c.selected)?.slot;status.textContent=['queued','starting'].includes(s.transport.state)?'音声を読み込み中…':s.comparisonLoading?`${s.comparisonLoading}へ切替中…`:selected?`${selected} ${s.transport.state==='playing'?'再生中':s.transport.state==='paused'?'一時停止':'選択中'}`:s.transport.busy?'反映中…':s.transport.state.toUpperCase();kind.textContent=s.transport.ready&&s.project?.id?({composition:'楽曲作成',mastering:'マスタリング',separation:'ステム分離'}[s.project.kind]??''):'';kind.hidden=!kind.textContent;clock.textContent=`${time(s.transport.position,s.transport.sampleRate)} / ${time(s.transport.duration,s.transport.sampleRate)}`;};}
export function createWaveform(root,dispatch,signal){
 const d=root.ownerDocument,strip=element(d,'button','waveform-strip'),img=element(d,'img');const measureContext=d.createElement('canvas').getContext('2d');const measureText=measureContext?(text,size,weight)=>{measureContext.font=`${weight} ${size}px -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif`;return measureContext.measureText(text).width;}:undefined;strip.type='button';strip.setAttribute('aria-label','曲全体の波形・再生位置');img.alt='';img.draggable=false;strip.append(img);root.append(strip);let touching=false,lastSrc='',imageGeneration=0;
 const seek=e=>{const r=strip.getBoundingClientRect();void dispatch({type:'transport.seek',ratio:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width))});};
 strip.addEventListener('pointerdown',e=>{if(strip.disabled)return;touching=true;strip.setPointerCapture(e.pointerId);seek(e);},{signal});
 strip.addEventListener('pointermove',e=>{if(touching)seek(e);},{signal});strip.addEventListener('pointerup',e=>{if(touching)seek(e);touching=false;},{signal});strip.addEventListener('pointercancel',()=>{touching=false;},{signal});
 strip.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home'].includes(e.code)){e.preventDefault();void dispatch(e.code==='Home'?{type:'transport.home'}:{type:'transport.seekRelative',seconds:e.code==='ArrowLeft'?-5:5});}},{signal});
 return s=>{const selected=s.comparisons?.find(c=>c.selected);strip.setAttribute('aria-label',selected?`${selected.slot} · ${selected.label} · 波形と再生位置`:'曲全体の波形・再生位置');strip.disabled=!s.actions.seek;const duration=s.transport.duration;const src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(renderWaveformSvg({peaks:s.waveform.peaks,layers:s.waveform.layers,positionRatio:duration?s.transport.position/duration:0,overlay:s.overlay,comparison:s.comparisons?.find(c=>c.selected),comparisons:s.comparisons,measureText,role:s.waveform.role,available:s.waveform.available}));if(src!==lastSrc){lastSrc=src;const generation=++imageGeneration;if(!img.getAttribute('src'))img.src=src;else{const ready=new d.defaultView.Image();ready.src=src;void ready.decode().then(()=>{if(!signal.aborted&&generation===imageGeneration)img.src=src;}).catch(()=>{});}}strip.title=[...(s.comparisons??[]).map(c=>`${c.slot}: ${c.label}`),s.waveform.role==='stems'?'再生対象ステムの重ね合わせ: '+(s.waveform.layers??[]).filter(l=>l.audible).map(l=>l.name).join(' / '):s.waveform.role==='processed_mix'?'処理後の波形':'原音の波形','RMS / Peak: dBFS · 各音の直近400ms','触れた位置へ移動'].join('\n');};
}
