import {renderWaveformSvg} from '../../Core/Source/ControlSurface/waveform.mjs';
export const time=(frames,rate)=>{const s=Math.floor(frames/rate);return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;};
export function element(doc,tag,className,text){const el=doc.createElement(tag);if(className)el.className=className;if(text)el.textContent=text;return el;}
export function createDisplay(root){const d=root.ownerDocument,art=element(d,'img','surface-artwork'),box=element(d,'div','display'),meta=element(d,'div','meta'),status=element(d,'p','state'),info=element(d,'div','song-info'),tempo=element(d,'span','tempo'),title=element(d,'h2'),readout=element(d,'div','readout'),kind=element(d,'div','project-kind'),clock=element(d,'div','playback-time');readout.append(kind,clock);info.append(status,tempo);meta.append(info,title);box.append(meta,readout);art.alt='';art.hidden=true;art.setAttribute('aria-hidden','true');let artworkUrl=null;art.onload=()=>{if(artworkUrl){art.hidden=false;root.classList.add('has-artwork');}};art.onerror=()=>{art.hidden=true;root.classList.remove('has-artwork');};root.classList.remove('has-artwork');root.append(art,box);return s=>{if(artworkUrl!==(s.artworkUrl??null)){artworkUrl=s.artworkUrl??null;art.hidden=true;root.classList.remove('has-artwork');if(artworkUrl)art.src=artworkUrl;else art.removeAttribute('src');}title.textContent=s.title;tempo.hidden=!(Number.isFinite(s.tempoBpm)&&s.tempoBpm>0);tempo.textContent=tempo.hidden?'':`${s.tempoBpm} BPM`;status.textContent=s.transport.busy?'反映中…':s.transport.state.toUpperCase();kind.textContent=s.transport.ready&&s.project?.id?({composition:'楽曲作成',mastering:'マスタリング',separation:'ステム分離'}[s.project.kind]??''):'';kind.hidden=!kind.textContent;clock.textContent=`${time(s.transport.position,s.transport.sampleRate)} / ${time(s.transport.duration,s.transport.sampleRate)}`;};}
export function createWaveform(root,dispatch,signal){
 const d=root.ownerDocument,strip=element(d,'button','waveform-strip'),img=element(d,'img');strip.type='button';strip.setAttribute('aria-label','曲全体の波形・再生位置');img.alt='';img.draggable=false;strip.append(img);root.append(strip);let touching=false;
 const seek=e=>{const r=strip.getBoundingClientRect();void dispatch({type:'transport.seek',ratio:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width))});};
 strip.addEventListener('pointerdown',e=>{if(strip.disabled)return;touching=true;strip.setPointerCapture(e.pointerId);seek(e);},{signal});
 strip.addEventListener('pointermove',e=>{if(touching)seek(e);},{signal});strip.addEventListener('pointerup',e=>{if(touching)seek(e);touching=false;},{signal});strip.addEventListener('pointercancel',()=>{touching=false;},{signal});
 strip.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home'].includes(e.code)){e.preventDefault();void dispatch(e.code==='Home'?{type:'transport.home'}:{type:'transport.seekRelative',seconds:e.code==='ArrowLeft'?-5:5});}},{signal});
 return s=>{strip.disabled=!s.actions.seek;const duration=s.transport.duration;img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(renderWaveformSvg({peaks:s.waveform.peaks,positionRatio:duration?s.transport.position/duration:0,overlay:s.overlay,available:s.waveform.available}));strip.title=s.waveform.available?'波形 · 触れた位置へ移動':'波形未生成 · 触れた位置へ移動';};
}
