/** Portable DSP plan. No JUCE XML, native field names, or executable payloads. */
export interface ParameterValue {id:string;value:number}
export interface Automation {parameter_id:string;interpolation:'linear'|'hold';points:Array<{tick?:number;frame?:string;value:number}>}
export interface ProcessorReference {kind:'plugin';plugin_id:string;plugin_version?:string;state_base64?:string;program?:number;parameters:ParameterValue[];automation?:Automation[]}
export interface MidiEvent {id:string;tick:number;duration:number;pitch:number;velocity:number;channel:number}
export interface AudioClip {start_frame:string;end_frame?:string;timeline_frame:string;fade_in_frames:string;fade_out_frames:string}
export type SignalSource={type:'processor';processor:ProcessorReference}|{type:'test-tone';sound:'sine'|'keys'|'bass'|'drums'}|{type:'audio';file:string;clip:AudioClip}|{type:'frozen';file:string;gain_db:number};
export interface PlanChannel {id:string;name:string;source:SignalSource;events:MidiEvent[];automation:Automation[];processors:ProcessorReference[];level:{gain_db:number;pan:number;mode:'unity'|'fader';pan_mode:'balance'|'pan';mute:boolean;solo:boolean;to_master:boolean};sends:Array<{bus_id:string;gain_db:number;position:'pre_fader'|'post_fader';enabled:boolean}>}
export interface PlanReturn {id:string;name:string;processors:ProcessorReference[];gain_db:number;pan:number;mute:boolean;solo:boolean}
export interface AudioPlan {contract:'aidaw.audio-plan';version:1;provenance:{id:string;name:string;revision:number};timing:{sample_rate:number;ppq:number;bpm:number;meter:[number,number];length_ticks:number;duration_frames?:string};channels:PlanChannel[];returns:PlanReturn[];master:{processors:ProcessorReference[];gain_db:number}}
const object=(v:unknown):Record<string,unknown>=>{if(!v||typeof v!=='object'||Array.isArray(v))throw Error('Expected DSP input object');return v as Record<string,unknown>;};
const str=(v:unknown,fallback?:string):string=>{if(v===undefined&&fallback!==undefined)return fallback;if(typeof v!=='string')throw Error('Expected DSP string');return v;};
const num=(v:unknown,fallback?:number):number=>{if(v===undefined&&fallback!==undefined)return fallback;if(typeof v!=='number'||!Number.isFinite(v))throw Error('Expected finite DSP number');return v;};
const bool=(v:unknown,fallback:boolean):boolean=>{if(v===undefined)return fallback;if(typeof v!=='boolean')throw Error('Expected DSP boolean');return v;};
const list=(v:unknown):unknown[]=>{if(v===undefined)return [];if(!Array.isArray(v))throw Error('Expected DSP array');return v;};
const normalized=(v:unknown)=>{const n=num(v);if(n<0||n>1)throw Error('Normalized parameter value out of range');return n;};
function automation(input:unknown):Automation[]{return list(input).map(raw=>{const a=object(raw),interpolation=a.interpolation??'linear';if(interpolation!=='linear'&&interpolation!=='hold')throw Error('Unsupported automation interpolation');return {parameter_id:str(a.parameter_id),interpolation,points:list(a.points).map(raw=>{const p=object(raw);return {...(p.tick!==undefined?{tick:num(p.tick)}:{frame:str(p.frame)}),value:normalized(p.value)};})};});}
export function processorReference(input:unknown):ProcessorReference{const p=object(input);if(p.kind!=='plugin')throw Error('Expected plugin reference');return {kind:'plugin',plugin_id:str(p.plugin_id),...(p.plugin_version!==undefined?{plugin_version:str(p.plugin_version)}:{}),...(p.state_base64!==undefined?{state_base64:str(p.state_base64)}:{}),...(p.program!==undefined?{program:num(p.program)}:{}),parameters:list(p.parameters).map(raw=>{const v=object(raw);return {id:str(v.id),value:normalized(v.value)};}),...(p.automation!==undefined?{automation:automation(p.automation)}:{})};}
const processors=(input:unknown)=>list(input).map(processorReference);
/** Translate authored/resolved application graph into the portable plan once, before driver invocation. */
export function audioPlan(input:unknown):AudioPlan{
 const g=object(input),meter=list(g.meter??[4,4]);if(meter.length!==2)throw Error('Invalid meter');
 return {contract:'aidaw.audio-plan',version:1,provenance:{id:str(g.id,'plan'),name:str(g.name,''),revision:num(g.revision,0)},timing:{sample_rate:num(g.sample_rate,48000),ppq:num(g.ppq,960),bpm:num(g.bpm,120),meter:[num(meter[0]),num(meter[1])],length_ticks:num(g.length_ticks,1),...(g.duration_frames!==undefined?{duration_frames:str(g.duration_frames)}:{})},channels:list(g.tracks).map(raw=>{
  const t=object(raw),instrument=object(t.instrument??{kind:'builtin',sound:'sine'});let source:SignalSource;
  if(t.rendered_audio_path!==undefined)source={type:'frozen',file:str(t.rendered_audio_path),gain_db:num(t.cached_gain_db,0)};
  else if(t.audio_source_path!==undefined){const c=object(t.audio_clip??{});source={type:'audio',file:str(t.audio_source_path),clip:{start_frame:str(c.start_frame,'0'),...(c.end_frame!==undefined?{end_frame:str(c.end_frame)}:{}),timeline_frame:str(c.timeline_frame,'0'),fade_in_frames:str(c.fade_in_frames,'0'),fade_out_frames:str(c.fade_out_frames,'0')}};}
  else if(instrument.kind==='plugin')source={type:'processor',processor:processorReference(instrument)};
  else if(instrument.kind==='builtin'){const sound=str(instrument.sound);if(!['sine','keys','bass','drums'].includes(sound))throw Error('Unknown test instrument');source={type:'test-tone',sound:sound as 'sine'|'keys'|'bass'|'drums'};}
  else throw Error('Unresolved DSP source');
  return {id:str(t.id),name:str(t.name,''),source,events:list(t.notes).map(raw=>{const n=object(raw);return {id:str(n.id),tick:num(n.tick),duration:num(n.duration),pitch:num(n.pitch),velocity:num(n.velocity),channel:num(n.channel,1)};}),automation:automation(t.automation),processors:processors(t.effects),level:{gain_db:num(t.gain_db,0),pan:num(t.pan,0),mode:bool(t.unity_gain,false)?'unity':'fader',pan_mode:instrument.kind==='audio'?'balance':'pan',mute:bool(t.mute,false),solo:bool(t.solo,false),to_master:bool(t.to_master,true)},sends:list(t.sends).map(raw=>{const send=object(raw),position=send.position??'post_fader';if(position!=='pre_fader'&&position!=='post_fader')throw Error('Invalid send position');return {bus_id:str(send.bus_id),gain_db:num(send.gain_db,0),position,enabled:bool(send.enabled,true)};})};
 }),returns:list(g.buses).map(raw=>{const b=object(raw);return {id:str(b.id),name:str(b.name,''),processors:processors(b.effects),gain_db:num(b.gain_db,0),pan:num(b.pan,0),mute:bool(b.mute,false),solo:bool(b.solo,false)};}),master:{processors:processors(g.master_effects),gain_db:num(g.master_gain_db,0)}};
}
